---
# tasks file for man

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: man

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: man

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: man
