---
# tasks file for man (Ubuntu specific)

- name: Install man packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ man_packages }}"
  tags:
    - man
